language: python
python:
    - '3.6'
    - '2.7'
install:
    - pip install 'numpy>=1.14'
    - pip install 'keras==2.1.3'
    - pip install 'opencv-python>=3.3.0'
    - pip install 'pillow'
    - pip install 'tensorflow'
    - pip install 'git+https://github.com/broadinstitute/keras-resnet'
    - pip install 'pytest-pep8'
    - pip install 'cython'
    - pip install 'matplotlib'
    - pip install 'h5py'
    - pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
cache: pip
script:
    - py.test --pep8
