language: python
sudo: required
python:
    - '3.6'
    - '2.7'
install:
    - pip install 'numpy>=1.14'
    - pip install 'keras==2.2.2'
    - pip install 'opencv-python>=3.3.0'
    - pip install 'pillow'
    - pip install 'tensorflow'
    - pip install 'git+https://github.com/broadinstitute/keras-resnet'
    - pip install 'pytest-flake8'
    - pip install 'pytest-xdist'
    - pip install 'cython'
    - pip install 'matplotlib'
    - pip install 'h5py'
    - pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
cache: pip
script:
    - python setup.py build_ext --inplace
    - py.test --flake8 --forked
